### ISSUE TITLE
Failing to build with Gazebo 10 (Fedora 32)

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/gazebo-rcll#23]
This repository fails to build on Fedora 32 with Gazebo 10.1:

```
         --> Entering sub-directory src/plugins/mps
            [C++] src/plugins/mps/ring_station.cpp
In file included from /usr/include/gazebo-10/gazebo/transport/Connection.hh:21,
                 from /usr/include/gazebo-10/gazebo/transport/transport.hh:3,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/mps.h:28,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.h:29,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.cpp:23:
/usr/include/tbb/task.h:21:139: note: ‘#pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.’
   21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                                                                                           ^
/home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.cpp: In member function ‘void gazebo::RingStation::publish_indicator(bool, int)’:
/home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.cpp:73:85: error: invalid use of incomplete type ‘class gazebo::common::Color’
   73 |     msgs::Set(msg.mutable_material()->mutable_diffuse(), gazebo::common::Color(1,0,0));
      |                                                                                     ^
In file included from /usr/include/gazebo-10/gazebo/physics/Model.hh:27,
                 from /usr/include/gazebo-10/gazebo/physics/Actor.hh:27,
                 from /usr/include/gazebo-10/gazebo/physics/physics.hh:2,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/mps.h:25,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.h:29,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.cpp:23:
/usr/include/gazebo-10/gazebo/common/CommonTypes.hh:76:11: note: forward declaration of ‘class gazebo::common::Color’
   76 |     class Color;
      |           ^~~~~
/home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.cpp:77:87: error: invalid use of incomplete type ‘class gazebo::common::Color’
   77 |     msgs::Set(msg.mutable_material()->mutable_diffuse(), gazebo::common::Color(0.3,0,0));
      |                                                                                       ^
In file included from /usr/include/gazebo-10/gazebo/physics/Model.hh:27,
                 from /usr/include/gazebo-10/gazebo/physics/Actor.hh:27,
                 from /usr/include/gazebo-10/gazebo/physics/physics.hh:2,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/mps.h:25,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.h:29,
                 from /home/thofmann/code/gazebo-rcll/plugins/src/plugins/mps/ring_station.cpp:23:
/usr/include/gazebo-10/gazebo/common/CommonTypes.hh:76:11: note: forward declaration of ‘class gazebo::common::Color’
   76 |     class Color;
      |           ^~~~~
make[5]: *** [/home/thofmann/code/gazebo-rcll/plugins/etc/buildsys/rules.mk:176: ring_station.o] Error 1
make[4]: *** [/home/thofmann/code/gazebo-rcll/plugins/etc/buildsys/objsdir.mk:34: .objs_fawkes] Error 2
make[3]: *** [/home/thofmann/code/gazebo-rcll/plugins/etc/buildsys/rules.mk:149: mps] Error 2
make[2]: *** [/home/thofmann/code/gazebo-rcll/plugins/etc/buildsys/rules.mk:149: plugins] Error 2
make[1]: *** [/home/thofmann/code/gazebo-rcll/plugins/etc/buildsys/rules.mk:149: src] Error 2
make: *** [/home/thofmann/code/gazebo-rcll/plugins/etc/buildsys/rules.mk:149: plugins] Error 2
```

**Comment by MostafaGomaa** [comment]
This is still an issue, is there a way I can re-open this!

**Comment by morxa** [comment]
Press the "Reopen" button?

**Comment by MostafaGomaa** [comment]
I didnt have the rights! There was no re-open

**Comment by morxa** [comment]
Fixed in #26.
